/**
 * deploy-web.ts
 *
 * Builds the Next.js frontend with production URLs fetched live from
 * CloudFormation, uploads the static export to S3, and invalidates CloudFront.
 *
 * Usage:
 *   pnpm run deploy:web                     # defaults to dev + eu-west-1
 *   ENVIRONMENT=prod pnpm run deploy:web
 *
 * AWS credentials are resolved from the default credential chain
 * (AWS_PROFILE env var, ~/.aws/credentials, IAM role, etc.).
 */

import {
  CloudFormationClient,
  DescribeStacksCommand,
} from "@aws-sdk/client-cloudformation";
import {
  CloudFrontClient,
  CreateInvalidationCommand,
  GetInvalidationCommand,
  ListDistributionsCommand,
} from "@aws-sdk/client-cloudfront";
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";

const ROOT = join(__dirname, "..");
const environment = process.env["ENVIRONMENT"] ?? "dev";
const region = process.env["AWS_REGION"] ?? "eu-west-1";

const cfnClient = new CloudFormationClient({ region });
// CloudFront is a global service — its API endpoint lives in us-east-1.
const cfrontClient = new CloudFrontClient({ region: "us-east-1" });

function exec(cmd: string, env?: Record<string, string>): void {
  console.log(`  $ ${cmd}`);
  execSync(cmd, {
    stdio: "inherit",
    cwd: ROOT,
    env: { ...process.env, ...env },
  });
}

async function getStackOutputs(
  stackName: string,
): Promise<Record<string, string>> {
  const { Stacks } = await cfnClient.send(
    new DescribeStacksCommand({ StackName: stackName }),
  );
  const stack = Stacks?.[0];
  if (!stack) throw new Error(`Stack "${stackName}" not found`);
  const out: Record<string, string> = {};
  for (const o of stack.Outputs ?? []) {
    if (o.OutputKey && o.OutputValue) out[o.OutputKey] = o.OutputValue;
  }
  return out;
}

async function getDistributionId(domainName: string): Promise<string> {
  const { DistributionList } = await cfrontClient.send(
    new ListDistributionsCommand({}),
  );
  const dist = DistributionList?.Items?.find(
    (d) => d.DomainName === domainName,
  );
  if (!dist?.Id)
    throw new Error(
      `No CloudFront distribution found for domain: ${domainName}`,
    );
  return dist.Id;
}

async function waitForInvalidation(
  distributionId: string,
  invalidationId: string,
): Promise<void> {
  // Poll every 5s until the invalidation reaches "Completed" status.
  // CloudFront invalidations typically complete in 30–60s.
  for (;;) {
    await new Promise((r) => setTimeout(r, 5000));
    const { Invalidation } = await cfrontClient.send(
      new GetInvalidationCommand({
        DistributionId: distributionId,
        Id: invalidationId,
      }),
    );
    if (Invalidation?.Status === "Completed") return;
    process.stdout.write(".");
  }
}

async function main(): Promise<void> {
  console.log(`\n🚀 Deploying BBTG Nieuws web (environment: ${environment})\n`);

  // ── 1. Resolve production URLs from CloudFormation ──────────────────────
  console.log("📡 Fetching stack outputs from CloudFormation...");
  const [apiOutputs, frontendOutputs] = await Promise.all([
    getStackOutputs(`bbtg-news-${environment}-api`),
    getStackOutputs(`bbtg-news-${environment}-frontend`),
  ]);

  const apiGatewayUrl = apiOutputs["ApiGatewayUrl"];
  const albDnsName = apiOutputs["AlbDnsName"];
  const bucketName = frontendOutputs["WebsiteBucketName"];
  const distributionDomain = frontendOutputs["DistributionDomainName"];

  if (!apiGatewayUrl || !albDnsName || !bucketName || !distributionDomain) {
    throw new Error(
      "One or more required CloudFormation outputs are missing. " +
        "Make sure the infra stacks are deployed first (`pnpm run deploy:infra`).",
    );
  }

  const sseUrl = `http://${albDnsName}`;
  console.log(`  API Gateway : ${apiGatewayUrl}`);
  console.log(`  SSE (ALB)   : ${sseUrl}`);
  console.log(`  S3 bucket   : ${bucketName}`);
  console.log(`  CloudFront  : https://${distributionDomain}\n`);

  const distributionId = await getDistributionId(distributionDomain);
  console.log(`  Distribution: ${distributionId}\n`);

  // ── 2. Write .env.production.local for the production build ──────────────
  // Next.js loads env files in this priority order during `next build`:
  //   .env.production.local > .env.local > .env.production > .env
  // By writing to .env.production.local we avoid overwriting .env.local,
  // which is reserved for local development (localhost URLs).
  // `next dev` ignores .env.production.local entirely — no more stale config.
  const envProdLocalPath = join(ROOT, "apps/web/.env.production.local");
  writeFileSync(
    envProdLocalPath,
    [
      "# Auto-generated by scripts/deploy-web.ts — do not edit manually",
      `NEXT_PUBLIC_API_URL=https://${distributionDomain}`,
      "",
    ].join("\n"),
  );
  console.log(`  Wrote ${envProdLocalPath}\n`);

  // ── 3. Invalidate API cache before building ──────────────────────────────
  // next build fetches blog/article data from NEXT_PUBLIC_API_URL (CloudFront).
  // If CloudFront has stale API responses cached, the built HTML will contain
  // old data. We invalidate API paths first and wait for completion so the
  // build always fetches fresh data from DynamoDB.
  console.log("🌐 Pre-build: invalidating API cache in CloudFront...");
  const { Invalidation: preInvalidation } = await cfrontClient.send(
    new CreateInvalidationCommand({
      DistributionId: distributionId,
      InvalidationBatch: {
        CallerReference: `pre-build-${randomUUID()}`,
        Paths: { Quantity: 2, Items: ["/blogs*", "/articles*"] },
      },
    }),
  );
  console.log(
    `  Invalidation ${preInvalidation?.Id} submitted, waiting for completion...`,
  );
  await waitForInvalidation(distributionId, preInvalidation?.Id ?? "");
  console.log("  API cache cleared ✓\n");

  // ── 4. Seed DynamoDB with demo data ─────────────────────────────────────
  // Seed runs *before* next build so generateStaticParams and any SSR fetches
  // find data in DynamoDB. The seed script is idempotent — it prunes all
  // tables before re-inserting, so re-deploying is always safe.
  console.log("🌱 Seeding DynamoDB with demo data...");
  exec("npx tsx scripts/seed.ts", {
    EDITORIAL_ARTICLES_TABLE: `${environment}-editorial-articles`,
    EDITORIAL_BLOGS_TABLE: `${environment}-editorial-blogs`,
    EDITORIAL_UPDATES_TABLE: `${environment}-editorial-updates`,
    DELIVERY_ARTICLES_TABLE: `${environment}-delivery-articles`,
    DELIVERY_BLOGS_TABLE: `${environment}-delivery-blogs`,
    DELIVERY_UPDATES_TABLE: `${environment}-delivery-updates`,
    DELIVERY_CHAT_MESSAGES_TABLE: `${environment}-delivery-chat-messages`,
    // ElastiCache is inside the VPC — not reachable from a developer laptop.
    // DynamoDB tables are seeded; Redis Streams will be populated when the
    // first live updates are posted via the API.
    SKIP_REDIS: "true",
    // Omit DYNAMODB_ENDPOINT so the AWS SDK uses the real endpoint.
  });
  console.log("  Seed complete ✓\n");

  // ── 5. Build Next.js static export ──────────────────────────────────────
  console.log("🏗️  Building Next.js static export...");
  exec("pnpm --filter @bbtg-news/web build");

  // ── 6. Upload to S3 with correct cache headers ───────────────────────────
  // Two-pass sync:
  //   Pass 1 — all non-HTML assets (JS, CSS, fonts, images): immutable long cache
  //   Pass 2 — HTML files only: no-cache so browsers always fetch the latest shell
  console.log("\n📦 Uploading to S3...");
  exec(
    `aws s3 sync apps/web/out/ s3://${bucketName} --delete ` +
      `--cache-control "public, max-age=31536000, immutable" --exclude "*.html"`,
  );
  exec(
    `aws s3 sync apps/web/out/ s3://${bucketName} ` +
      `--cache-control "no-cache" --exclude "*" --include "*.html"`,
  );

  // ── 7. Invalidate CloudFront ─────────────────────────────────────────────
  console.log("\n🌐 Invalidating CloudFront cache...");
  const { Invalidation } = await cfrontClient.send(
    new CreateInvalidationCommand({
      DistributionId: distributionId,
      InvalidationBatch: {
        CallerReference: randomUUID(),
        Paths: { Quantity: 1, Items: ["/*"] },
      },
    }),
  );
  console.log(`  Invalidation ${Invalidation?.Id}: ${Invalidation?.Status}`);

  console.log(`\n✅ Done! https://${distributionDomain}\n`);
}

main().catch((err: unknown) => {
  console.error("\n❌ Deploy failed:", err);
  process.exit(1);
});
