/**
 * deploy-web.ts
 *
 * Builds the Next.js frontend with production URLs fetched live from
 * CloudFormation, uploads the static export to S3, and invalidates CloudFront.
 *
 * Usage:
 *   pnpm run deploy:web                     # defaults to dev + eu-west-1
 *   ENVIRONMENT=prod pnpm run deploy:web
 *
 * AWS credentials are resolved from the default credential chain
 * (AWS_PROFILE env var, ~/.aws/credentials, IAM role, etc.).
 */

import {
  CloudFormationClient,
  DescribeStacksCommand,
} from "@aws-sdk/client-cloudformation";
import {
  CloudFrontClient,
  CreateInvalidationCommand,
  ListDistributionsCommand,
} from "@aws-sdk/client-cloudfront";
import { execSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { randomUUID } from "node:crypto";

const ROOT = join(__dirname, "..");
const environment = process.env["ENVIRONMENT"] ?? "dev";
const region = process.env["AWS_REGION"] ?? "eu-west-1";

const cfnClient = new CloudFormationClient({ region });
// CloudFront is a global service — its API endpoint lives in us-east-1.
const cfrontClient = new CloudFrontClient({ region: "us-east-1" });

function exec(cmd: string, env?: Record<string, string>): void {
  console.log(`  $ ${cmd}`);
  execSync(cmd, {
    stdio: "inherit",
    cwd: ROOT,
    env: { ...process.env, ...env },
  });
}

async function getStackOutputs(
  stackName: string,
): Promise<Record<string, string>> {
  const { Stacks } = await cfnClient.send(
    new DescribeStacksCommand({ StackName: stackName }),
  );
  const stack = Stacks?.[0];
  if (!stack) throw new Error(`Stack "${stackName}" not found`);
  const out: Record<string, string> = {};
  for (const o of stack.Outputs ?? []) {
    if (o.OutputKey && o.OutputValue) out[o.OutputKey] = o.OutputValue;
  }
  return out;
}

async function getDistributionId(domainName: string): Promise<string> {
  const { DistributionList } = await cfrontClient.send(
    new ListDistributionsCommand({}),
  );
  const dist = DistributionList?.Items?.find((d) => d.DomainName === domainName);
  if (!dist?.Id)
    throw new Error(`No CloudFront distribution found for domain: ${domainName}`);
  return dist.Id;
}

async function main(): Promise<void> {
  console.log(`\n🚀 Deploying BBTG Nieuws web (environment: ${environment})\n`);

  // ── 1. Resolve production URLs from CloudFormation ──────────────────────
  console.log("📡 Fetching stack outputs from CloudFormation...");
  const [apiOutputs, frontendOutputs] = await Promise.all([
    getStackOutputs(`bbtg-news-${environment}-api`),
    getStackOutputs(`bbtg-news-${environment}-frontend`),
  ]);

  const apiGatewayUrl = apiOutputs["ApiGatewayUrl"];
  const albDnsName = apiOutputs["AlbDnsName"];
  const bucketName = frontendOutputs["WebsiteBucketName"];
  const distributionDomain = frontendOutputs["DistributionDomainName"];

  if (!apiGatewayUrl || !albDnsName || !bucketName || !distributionDomain) {
    throw new Error(
      "One or more required CloudFormation outputs are missing. " +
        "Make sure the infra stacks are deployed first (`pnpm run deploy:infra`).",
    );
  }

  const sseUrl = `http://${albDnsName}`;
  console.log(`  API Gateway : ${apiGatewayUrl}`);
  console.log(`  SSE (ALB)   : ${sseUrl}`);
  console.log(`  S3 bucket   : ${bucketName}`);
  console.log(`  CloudFront  : https://${distributionDomain}\n`);

  const distributionId = await getDistributionId(distributionDomain);
  console.log(`  Distribution: ${distributionId}\n`);

  // ── 2. Write .env.local so Next.js picks up the correct URLs ────────────
  // Next.js reads .env.local with higher priority than command-line env vars
  // for NEXT_PUBLIC_* substitution at build time. We overwrite it here so
  // the built JS bundles always contain the live production endpoints.
  const envLocalPath = join(ROOT, "apps/web/.env.local");
  writeFileSync(
    envLocalPath,
    [
      "# Auto-generated by scripts/deploy-web.ts",
      "# Restore to localhost:3001 for local development",
      `NEXT_PUBLIC_API_URL=https://${distributionDomain}`,
      "API_URL=http://localhost:3001",
      "",
    ].join("\n"),
  );
  console.log(`  Wrote ${envLocalPath}\n`);

  // ── 3. Build Next.js static export ──────────────────────────────────────
  console.log("🏗️  Building Next.js static export...");
  exec("pnpm --filter @bbtg-news/web build");

  // ── 4. Upload to S3 with correct cache headers ───────────────────────────
  // Two-pass sync:
  //   Pass 1 — all non-HTML assets (JS, CSS, fonts, images): immutable long cache
  //   Pass 2 — HTML files only: no-cache so browsers always fetch the latest shell
  console.log("\n📦 Uploading to S3...");
  exec(
    `aws s3 sync apps/web/out/ s3://${bucketName} --delete ` +
      `--cache-control "public, max-age=31536000, immutable" --exclude "*.html"`,
  );
  exec(
    `aws s3 sync apps/web/out/ s3://${bucketName} ` +
      `--cache-control "no-cache" --exclude "*" --include "*.html"`,
  );

  // ── 5. Invalidate CloudFront ─────────────────────────────────────────────
  console.log("\n🌐 Invalidating CloudFront cache...");
  const { Invalidation } = await cfrontClient.send(
    new CreateInvalidationCommand({
      DistributionId: distributionId,
      InvalidationBatch: {
        CallerReference: randomUUID(),
        Paths: { Quantity: 1, Items: ["/*"] },
      },
    }),
  );
  console.log(`  Invalidation ${Invalidation?.Id}: ${Invalidation?.Status}`);

  console.log(`\n✅ Done! https://${distributionDomain}\n`);
}

main().catch((err: unknown) => {
  console.error("\n❌ Deploy failed:", err);
  process.exit(1);
});
